// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Songs.Models;

#nullable disable

namespace Songs.Solution.Migrations
{
    [DbContext(typeof(SongContext))]
    partial class SongContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Songs.Models.Song", b =>
                {
                    b.Property<int>("SongId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Artist")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("SongId");

                    b.ToTable("Songs");

                    b.HasData(
                        new
                        {
                            SongId = 1,
                            Artist = "Queen",
                            Name = "Eye of the Tiger",
                            Year = 1980
                        },
                        new
                        {
                            SongId = 2,
                            Artist = "Bright Eyes",
                            Name = "First Day of My Life",
                            Year = 1999
                        },
                        new
                        {
                            SongId = 3,
                            Artist = "Queen",
                            Name = "Bohemian Rhapsody",
                            Year = 1978
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
